version: '2'
services:
  neo4j:
    image: neo4j:3.2
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017

  reporting-service:
    image: nickom/reporting-service:latest
    restart: always
    ports:
      - 8081:8081
