logging:
  level:
    com.nickom: INFO

spring:
  application:
    name: reporting-service
  profiles:
    active: dev
  data:
    # replace this with your local/dev credentials
    neo4j:
      uri: bolt://${NEO4J_HOST:localhost}
      username: neo4j
      password: admin
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/reporting

server:
  port: 8081

gcp:
  account:
    # Replace this with your GCP service account json path
    credential: '/gcp/NLP-Sentiment-12227a53e87a.json'

---

spring:
  profiles: dev

logging:
  level:
    com.nickom: DEBUG