logging:
  level:
    com.nickom: DEBUG

spring:
  application:
    name: reporting
  profiles:
    active: dev
  data:
    neo4j:
      # replace this with your local/dev credentials
      uri: bolt://localhost
      username: neo4j
      password: admin

---

spring:
  profiles: dev

server:
  port: 8081
